CREATE USER 'z2m'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'z2m'@'localhost' WITH GRANT OPTION;
CREATE USER 'z2m'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'z2m'@'%' WITH GRANT OPTION;
